name: release

on:
  push:
    tags:
      - v*.*.*

env:
    IMAGE_NAME: knoq-ui

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - run: npm run build
        env:
          NODE_ENV: production
      - name: Archive dist/
        run: tar -zcvf ./dist.tar.gz ./dist
      - name: Create Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: dist.tar.gz

  image:
      name: Build Docker Image
      runs-on: ubuntu-latest
      steps:
        - name: Set IMAGE_TAG env
          run: echo IMAGE_TAG=$(echo ${GITHUB_REF:11}) >> $GITHUB_ENV

        - uses: actions/checkout@4

        - name: Set up QEMU
          uses: docker/setup-qemu-action@v3
        - name: Set up Docker Buildx
          id: buildx
          uses: docker/setup-buildx-action@v3
        - name: Show available platforms
          run: echo ${{ steps.buildx.outputs.platforms }}
        - name: Login to GitHub Container Registry
          uses: docker/login-action@v3
          with:
            registry: ghcr.io
            username: traptitech
            password: ${{ secrets.GITHUB_TOKEN }}

        - name: Build and push
          uses: docker/build-push-action@v6
          with:
            context: .
            push: true
            platforms: linux/amd64,linux/arm64
            tags: |
                ghcr.io/traptitech/${{ env.IMAGE_NAME }}:latest
                ghcr.io/traptitech/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
            cache-from: type=registry,ref=ghcr.io/traptitech/${{ env.IMAGE_NAME }}:buildcache
